apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: staging
spec:
  cluster: staging
  kind: Permanent
  label: Staging
  namespace: staging
  order: 100
  previewGitInfo:
    user: {}
  promotionStrategy: Auto
  source:
    ref: master
    url: https://github.com/zp-config-ro/environment-zp-staging.git
  teamSettings: {}
status: {}
