jenkins-x-platform:
  PipelineSecrets:
    DockerConfig: |-
      {
        "credsStore": "ecr-login"
      }
  docker-registry:
    enabled: false
  expose:
    Annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-delete-policy: hook-succeeded
    config:
      domain: k8s.zenplanner.net
      exposer: Ingress
      http: "true"
  jenkins:
    Servers:
      Global:
        EnvVars:
          DOCKER_REGISTRY: 985291351041.dkr.ecr.us-east-1.amazonaws.com
          TILLER_NAMESPACE: kube-system
  postinstalljob:
    enabled: "true"
